diff --git a/Makefile b/Makefile
index 7fd1066..7f60820 100644
--- a/Makefile
+++ b/Makefile
@@ -2,6 +2,9 @@ VERSION		:=	"0.0.1"
 
 CC			:=	$(CROSS_COMPILE)gcc
 INCLUDES	:=	-I. \
+				-L$(CS_TOOLCHAIN_ROOT)/arm-none-linux-gnueabi/libc/usr/lib \
+				-Xlinker -rpath-link=/opt/arm-none-linux-gnueabi/usr/lib \
+				-L$(CROSS_COMPILE_ROOT)/usr/lib \
 				-I$(CROSS_COMPILE_ROOT)/usr/include/glib-2.0 \
 				-I$(CROSS_COMPILE_ROOT)/usr/lib/glib-2.0/include \
 				-I$(CROSS_COMPILE_ROOT)/usr/include/lunaservice \
