#!/bin/sh                                                                                       

PID="us.ryanhope.wircd"

# Install the upstart script
rm -f /etc/event.d/${PID}
cp $IPKG_OFFLINE_ROOT/etc/event.d/${PID} /etc/event.d/${PID}

# Install the service binary
rm -f /var/usr/bin/${PID}
mkdir -p /var/usr/bin
cp $IPKG_OFFLINE_ROOT/usr/bin/${PID} /var/usr/bin/${PID}

# Start the service
/sbin/start us.ryanhope.wircd

exit 0
