#!/bin/sh                                                                                       

PID="us.ryanhope.wircd"

if [ -z "$IPKG_OFFLINE_ROOT" ]; then
  IPKG_OFFLINE_ROOT=/var
fi

# Install the upstart script
rm -f /etc/event.d/${PID}
cp $IPKG_OFFLINE_ROOT/etc/event.d/${PID} /etc/event.d/${PID}

# Install the service binary
if [ "$IPKG_OFFLINE_ROOT" != "/var" ] ; then
  rm -f /var/usr/bin/${PID}
  mkdir -p /var/usr/bin
  cp $IPKG_OFFLINE_ROOT/usr/bin/${PID} /var/usr/bin/${PID}
fi

# Start the service
/sbin/start ${PID}

exit 0
