#!/bin/sh                                                                                       

PID="us.ryanhope.wircd"

# Install the upstart script
rm -f /etc/event.d/${PID}
cp /var/etc/event.d/${PID} /etc/event.d/${PID}

# Start the service
/sbin/start us.ryanhope.wircd

exit 0
