#!/bin/sh

PID="us.ryanhope.wircd"

# Stop the service
/sbin/stop ${PID}

# Remove the service binary
if [ "$IPKG_OFFLINE_ROOT" != "/var" ] ; then
  rm -f /var/usr/bin/${PID}
fi

# Remove the upstart script
rm -f /etc/event.d/${PID}

exit 0
